### ISSUE TITLE
Fix thread conflict between the two failing tests in SelectSportActivity and the map

### ISSUE THREAD

**Issue by Luca-Engel** [SDPCoachMe/SDP-2023#80]

**Comment by Ayskin** [comment]
The bug could not have been fixed within this sprint. I've started to work on this bug in the previous sprint and at that time the issue was not solved (see https://github.com/googlemaps/android-maps-compose/issues/211). As it is still an open issue to this day, I've tried for this sprint to find work-arounds to avoid the raised exception that makes the tests fail. The issue comes directly from the GoogleMap composable that we use in our project. If MapActivity is launched from another activity within tests, the loading of the GoogleMap crashes, while this behavior does not happen in our production application. So it has been decided for now to ignore the affected test cases, which is not very punitive as they only concern the loading of the map view on MapActivity redirection from other activities. Above all, this issue may even disappear in another application model (single activity using Jetpack's Navigation Component) that we may choose to implement in the future.
